spring:
  datasource:
    url: jdbc:mysql://db:3306/catalog_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      initialization-fail-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        
  redis:
    host: redis
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    connect-timeout: 60000ms
    
  cache:
    type: redis
    redis:
      time-to-live: 1800000
      cache-null-values: false
    
server:
  port: 8080
  address: 0.0.0.0

logging:
  level:
    org.springframework.cache: DEBUG
    org.hibernate.SQL: DEBUG
    com.catalog: DEBUG
